project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "*.md"
    - "!tmp/"

title: "Advanced Topics in Network Science"
author: Sadamori Kojaku
date: last-modified
date-format: long

website:
  title: "Advanced Topics in Network Science"
  repo-url: https://github.com/skojaku/adv-net-sci
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer:
    left: "Copyright 2024, Sadamori Kojaku"
    right:
      - icon: github
        href: https://github.com/skojaku/adv-net-sci

  navbar:
    logo: logo.jpg
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Intro"
        menu:
          - text: "Why Networks?"
            file: intro/why-networks.qmd
          - text: "Setup"
            file: intro/setup.qmd
      - text: "Dojo 🥋"
        menu:
          - text: "Quiz Dojo"
            file: dojo/quiz-dojo.qmd
      - text: "M01: Euler Tour"
        menu:
          - text: "Preparation"
            file: m01-euler_tour/00-preparation.qmd
          - text: "Concepts"
            file: m01-euler_tour/01-concepts.qmd
          - text: "Coding"
            file: m01-euler_tour/02-coding.qmd
          - text: "Exercises"
            file: m01-euler_tour/03-exercises.qmd
          - text: "Advanced"
            file: m01-euler_tour/04-advanced.qmd
      - text: "M02: Small World"
        menu:
          - text: "Preparation"
            file: m02-small-world/00-preparation.qmd
          - text: "Concepts"
            file: m02-small-world/01-concepts.qmd
          - text: "Coding"
            file: m02-small-world/02-coding.qmd
          - text: "Exercises"
            file: m02-small-world/03-exercises.md
          - text: "Appendix"
            file: m02-small-world/04-appendix.qmd
      - text: "M03: Robustness"
        menu:
          - text: "Preparation"
            file: m03-robustness/00-preparation.md
          - text: "Concepts"
            file: m03-robustness/01-concepts.qmd
          - text: "Coding"
            file: m03-robustness/02-coding.qmd
          - text: "Exercises"
            file: m03-robustness/03-exercises.qmd
          - text: "Appendix"
            file: m03-robustness/04-appendix.md
      - text: "M04: Friendship Paradox"
        menu:
          - text: "Preparation"
            file: m04-friendship-paradox/00-preparation.md
          - text: "Concepts"
            file: m04-friendship-paradox/01-concepts.md
          - text: "Coding"
            file: m04-friendship-paradox/02-coding.qmd
          - text: "Exercises"
            file: m04-friendship-paradox/03-exercises.md
      - text: "M05: Clustering"
        menu:
          - text: "Preparation"
            file: m05-clustering/00-preparation.md
          - text: "Concepts"
            file: m05-clustering/01-concepts.qmd
          - text: "Coding"
            file: m05-clustering/02-coding.qmd
          - text: "Exercises"
            file: m05-clustering/03-exercises.qmd
      - text: "M06: Centrality"
        menu:
          - text: "Preparation"
            file: m06-centrality/00-preparation.md
          - text: "Concepts"
            file: m06-centrality/01-concepts.qmd
          - text: "Coding"
            file: m06-centrality/02-coding.qmd
          - text: "Exercises"
            file: m06-centrality/03-exercises.md
      - text: "M07: Random Walks"
        menu:
          - text: "Preparation"
            file: m07-random-walks/00-preparation.md
          - text: "Concepts"
            file: m07-random-walks/01-concepts.qmd
          - text: "Coding"
            file: m07-random-walks/02-coding.qmd
          - text: "Exercises"
            file: m07-random-walks/03-exercises.qmd
      - text: "M08: Embedding"
        menu:
          - text: "Preparation"
            file: m08-embedding/00-preparation.md
          - text: "Concepts"
            file: m08-embedding/01-concepts.md
          - text: "Coding"
            file: m08-embedding/02-coding.qmd
          - text: "Exercises"
            file: m08-embedding/03-exercises.md
          - text: "Appendix"
            file: m08-embedding/04-appendix.md
      - text: "M09: Graph Neural Networks"
        menu:
          - text: "Preparation"
            file: m09-graph-neural-networks/00-preparation.md
          - text: "Concepts"
            file: m09-graph-neural-networks/01-concepts.md
          - text: "Coding"
            file: m09-graph-neural-networks/02-coding.qmd
          - text: "Exercises"
            file: m09-graph-neural-networks/03-exercises.qmd
          - text: "Appendix"
            file: m09-graph-neural-networks/04-appendix.qmd

execute:
  enabled: false  # Disable execution for initial migration
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - scss/style.scss
    toc: false
    page-layout: full
    toc-depth: 2
    number-sections: true
    number-depth: 2
    html-math-method: katex
    code-fold: false
    code-copy: hover
    code-tools: true
    fontsize: 21px
    margin-left: 50px
    margin-right: 50px
    css:
      - assets/custom.css

# Add a bibtex file so that we can create citations
bibliography: references.bib

