project:
  type: website
  output-dir: _site

title: "Advanced Topics in Network Science"
author: Sadamori Kojaku
date: last-modified
date-format: long

website:
  title: "Advanced Topics in Network Science"
  logo: logo.jpg
  repo-url: https://github.com/skojaku/adv-net-sci
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer:
    left: "Copyright 2024, Sadamori Kojaku"
    right:
      - icon: github
        href: https://github.com/skojaku/adv-net-sci
  
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Intro"
        menu:
          - intro/why-networks.md
          - intro/setup.md
      - text: "Dojo 🥋"
        menu:
          - dojo/quiz-dojo.md
      - text: "M01: Euler Tour"
        menu:
          - m01-euler_tour/00-preparation.qmd
          - m01-euler_tour/01-concepts.md
          - m01-euler_tour/02-coding.qmd
          - m01-euler_tour/03-exercises.qmd
          - m01-euler_tour/04-advanced.qmd
      - text: "M02: Small World"
        menu:
          - m02-small-world/00-preparation.md
          - m02-small-world/01-concepts.md
          - m02-small-world/02-coding.qmd
          - m02-small-world/03-exercises.md
          - m02-small-world/04-appendix.qmd
      - text: "M03: Robustness"
        menu:
          - m03-robustness/00-preparation.md
          - m03-robustness/01-concepts.md
          - m03-robustness/02-coding.qmd
          - m03-robustness/03-exercises.md
          - m03-robustness/04-appendix.md
      - text: "M04: Friendship Paradox"
        menu:
          - m04-friendship-paradox/00-preparation.md
          - m04-friendship-paradox/01-concepts.md
          - m04-friendship-paradox/02-coding.qmd
          - m04-friendship-paradox/03-exercises.md
      - text: "M05: Clustering"
        menu:
          - m05-clustering/00-preparation.md
          - m05-clustering/01-concepts.qmd
          - m05-clustering/02-coding.qmd
          - m05-clustering/03-exercises.qmd
      - text: "M06: Centrality"
        menu:
          - m06-centrality/00-preparation.md
          - m06-centrality/01-concepts.md
          - m06-centrality/02-coding.qmd
          - m06-centrality/03-exercises.md
      - text: "M07: Random Walks"
        menu:
          - m07-random-walks/00-preparation.md
          - m07-random-walks/01-concepts.qmd
          - m07-random-walks/02-coding.qmd
          - m07-random-walks/03-exercises.md
      - text: "M08: Embedding"
        menu:
          - m08-embedding/00-preparation.md
          - m08-embedding/01-concepts.md
          - m08-embedding/02-coding.qmd
          - m08-embedding/03-exercises.md
          - m08-embedding/04-appendix.md
      - text: "M09: Graph Neural Networks"
        menu:
          - m09-graph-neural-networks/00-preparation.md
          - m09-graph-neural-networks/01-concepts.md
          - m09-graph-neural-networks/02-coding.qmd
          - m09-graph-neural-networks/03-exercises.md
          - m09-graph-neural-networks/04-appendix.qmd

execute:
  enabled: true  # Disable execution for initial migration
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - scss/style.scss
    toc: false
    page-layout: full
    toc-depth: 2
    number-sections: true
    number-depth: 2
    html-math-method: katex
    code-fold: false
    code-copy: hover
    code-tools: true
    fontsize: 21px
    margin-left: 50px
    margin-right: 50px
    css:
      - assets/custom.css

# Add a bibtex file so that we can create citations
bibliography: references.bib

