project:
  type: book
  output-dir: _book

author: Sadamori Kojaku
date: last-modified
date-format: long

book:
  title: "Advanced Topics in Network Science"
  author: "Sadamori Kojaku"
  sidebar:
    logo: logo.jpg

  chapters:
    - index.qmd
    - part: "Intro"
      chapters:
        - intro/why-networks.md
        - intro/setup.md
    - part: "Dojo 🥋"
      chapters:
        - dojo/quiz-dojo.md
    - part: "M01: Euler Tour"
      chapters:
        - m01-euler_tour/00-preparation.md
        - m01-euler_tour/01-concepts.md
        - m01-euler_tour/02-coding.qmd
        - m01-euler_tour/03-exercises.qmd
    - part: "M02: Small World"
      chapters:
        - m02-small-world/00-preparation.md
        - m02-small-world/01-concepts.md
        - m02-small-world/02-coding.qmd
        - m02-small-world/03-exercises.md
        - m02-small-world/04-appendix.qmd
    - part: "M03: Robustness"
      chapters:
        - m03-robustness/00-preparation.md
        - m03-robustness/01-concepts.md
        - m03-robustness/02-coding.qmd
        - m03-robustness/03-exercises.md
        - m03-robustness/04-appendix.md
    - part: "M04: Friendship Paradox"
      chapters:
        - m04-friendship-paradox/00-preparation.md
        - m04-friendship-paradox/01-concepts.md
        - m04-friendship-paradox/02-coding.qmd
        - m04-friendship-paradox/03-exercises.md
    - part: "M05: Clustering"
      chapters:
        - m05-clustering/00-preparation.md
        - m05-clustering/01-concepts.qmd
        - m05-clustering/02-coding.qmd
        - m05-clustering/03-exercises.qmd
    - part: "M06: Centrality"
      chapters:
        - m06-centrality/00-preparation.md
        - m06-centrality/01-concepts.md
        - m06-centrality/02-coding.qmd
        - m06-centrality/03-exercises.md
    - part: "M07: Random Walks"
      chapters:
        - m07-random-walks/00-preparation.md
        - m07-random-walks/01-concepts.qmd
        - m07-random-walks/02-coding.qmd
        - m07-random-walks/03-exercises.md
    - part: "M08: Embedding"
      chapters:
        - m08-embedding/00-preparation.md
        - m08-embedding/01-concepts.md
        - m08-embedding/02-coding.qmd
        - m08-embedding/03-exercises.md
        - m08-embedding/04-appendix.md
    - part: "M09: Graph Neural Networks"
      chapters:
        - m09-graph-neural-networks/00-preparation.md
        - m09-graph-neural-networks/01-concepts.md
        - m09-graph-neural-networks/02-coding.qmd
        - m09-graph-neural-networks/03-exercises.md
        - m09-graph-neural-networks/04-appendix.qmd

execute:
  enabled: false  # Disable execution for initial migration
  freeze: auto

format:
  html:
    theme:
      light:
         - cosmo
         - scss/style.scss
      dark:
         - cosmo
         - scss/style.scss
    toc: false
    page-layout: full
    toc-depth: 2
    number-sections: true
    number-depth: 2
    html-math-method: katex
    code-fold: false
    code-copy: hover
    code-tools: true

# Add a bibtex file so that we can create citations
bibliography: references.bib

# Information about where the book exists on the web
website:
  repo-url: https://github.com/skojaku/adv-net-sci
  repo-actions: [edit, issue]
  search: true
  page-navigation: false
  page-footer:
    left: "Copyright 2024, Sadamori Kojaku"
    right:
      - icon: github
        href: https://github.com/skojaku/adv-net-sci
  navbar:
    top:
      - text: "More"
        menu:
           - text: "GitHub"
             href: https://github.com/skojaku/adv-net-sci
