project:
  type: book
  output-dir: _book


book:
  title: "Advanced Topics in Network Science"
  author: "Sadamori Kojaku"
  sidebar:
    logo: logo.jpg

  chapters:
    - index.qmd
    - part: "Intro"
      chapters:
        - intro/why-networks.md
        - intro/zoo-of-networks.md
        - intro/setup.md
    - part: "M01: Euler Tour"
      chapters:
        - m01-euler_tour/what-to-learn.md
        - m01-euler_tour/puzzle.md
        - m01-euler_tour/euler-path.md
        - m01-euler_tour/how-to-code-network.qmd
        - m01-euler_tour/coding-exercise.qmd
    - part: "M02: Small World"
      chapters:
        - m02-small-world/what-to-learn.md
        - m02-small-world/small-world-experiment.md
        - m02-small-world/wikirace.md
        - m02-small-world/pen-and-paper.md
        - m02-small-world/connectedness.md
        - m02-small-world/which-tools.md
        - m02-small-world/compressed-sparse-row.qmd
        - m02-small-world/connectedness-hands-on.qmd
        - m02-small-world/assignment.md
        - m02-small-world/appendix.qmd
    - part: "M03: Robustness"
      chapters:
        - m03-robustness/what-to-learn.md
        - m03-robustness/exercise-power-grid.md
        - m03-robustness/minimum-spanning-tree.qmd
        - m03-robustness/robustness.md
        - m03-robustness/robustness-hands-on.qmd
        - m03-robustness/percolation.qmd
        - m03-robustness/appendix.md
    - part: "M04: Friendship Paradox"
      chapters:
        - m04-friendship-paradox/what-to-learn.md
        - m04-friendship-paradox/experiment.md
        - m04-friendship-paradox/friendship-paradox.md
        - m04-friendship-paradox/vaccination-game.md
        - m04-friendship-paradox/degree-distribution.qmd
    - part: "M05: Clustering"
      chapters:
        - m05-clustering/what-to-learn.md
        - m05-clustering/what-is-community.md
        - m05-clustering/pen-and-paper.md
        - m05-clustering/pattern-matching.md
        - m05-clustering/graph-cut.md
        - m05-clustering/ratio-normalized-cut.qmd
        - m05-clustering/modularity.md
        - m05-clustering/modularity-02.qmd
        - m05-clustering/stochastic-block-model.qmd
        - m05-clustering/exercise-clustering.qmd
    - part: "M06: Centrality"
      chapters:
        - m06-centrality/what-to-learn.md
        - m06-centrality/pen-and-paper.md
        - m06-centrality/degree-distance-based-centrality.md
        - m06-centrality/eigencentrality.md
        - m06-centrality/hands-on.md
        - m06-centrality/assignment.md
    - part: "M07: Random Walks"
      chapters:
        - m07-random-walks/what-to-learn.md
        - m07-random-walks/amida-kuji.md
        - m07-random-walks/random-walks.qmd
        - m07-random-walks/pen-and-paper.md
        - m07-random-walks/random-walks-code.qmd
        - m07-random-walks/random-walks-math.qmd
        - m07-random-walks/unifying-centrality-and-communities.qmd
    - part: "M08: Embedding"
      chapters:
        - m08-embedding/what-to-learn.md
        - m08-embedding/pen-and-paper.md
        - m08-embedding/spectral-embedding.qmd
        - m08-embedding/word2vec.qmd
        - m08-embedding/graph-embedding-w-word2vec.qmd
        - m08-embedding/spectral-vs-neural-embedding.md
        - m08-embedding/software.md
        - m08-embedding/appendix.md
    - part: "M09: Graph Neural Networks"
      chapters:
        - m09-graph-neural-networks/00-preparation.md
        - m09-graph-neural-networks/01-concepts.md
        - m09-graph-neural-networks/02-coding.qmd
        - m09-graph-neural-networks/03-exercises.md
        - m09-graph-neural-networks/04-appendix.qmd

execute:
  enabled: false  # Disable execution for initial migration
  freeze: auto

format:
  html:
    theme: materia
    toc: true
    toc-depth: 3
    number-sections: true
    html-math-method: katex
    code-fold: true
    code-copy: hover
    code-tools: true

# Add a bibtex file so that we can create citations
bibliography: references.bib

# Information about where the book exists on the web
website:
  repo-url: https://github.com/skojaku/adv-net-sci
  repo-actions: [edit, issue]
  search: true
  page-navigation: true
  page-footer:
    left: "Copyright 2024, Sadamori Kojaku"
    right:
      - icon: github
        href: https://github.com/skojaku/adv-net-sci
  navbar:
    left:
      - text: "More"
        menu:
           - text: "GitHub"
             href: https://github.com/skojaku/adv-net-sci