project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "*.md"
    - "!tmp/"

title: "Advanced Topics in Network Science"
author: Sadamori Kojaku
date: last-modified
date-format: long

website:
  title: "Advanced Topics in Network Science"
  repo-url: https://github.com/skojaku/adv-net-sci
  repo-actions: [edit, issue]
  page-navigation: true
  reader-mode: true
  page-footer:
    left: "Copyright 2024, Sadamori Kojaku"
    right:
      - icon: github
        href: https://github.com/skojaku/adv-net-sci
  
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - section: "Introduction"
        contents:
          - intro/why-networks.qmd
          - intro/setup.qmd
          - dojo/quiz-dojo.qmd
      - section: "M01: Euler Tour"
        contents:
          - m01-euler_tour/00-preparation.qmd
          - m01-euler_tour/01-concepts.qmd
          - m01-euler_tour/02-coding.qmd
          - m01-euler_tour/03-exercises.qmd
          - m01-euler_tour/04-advanced.qmd
      - section: "M02: Small World"
        contents:
          - m02-small-world/00-preparation.qmd
          - m02-small-world/01-concepts.qmd
          - m02-small-world/02-coding.qmd
          - m02-small-world/03-exercises.md
          - m02-small-world/04-appendix.qmd
      - section: "M03: Robustness"
        contents:
          - m03-robustness/00-preparation.md
          - m03-robustness/01-concepts.qmd
          - m03-robustness/02-coding.qmd
          - m03-robustness/03-exercises.qmd
          - m03-robustness/04-appendix.md
      - section: "M04: Friendship Paradox"
        contents:
          - m04-friendship-paradox/00-preparation.md
          - m04-friendship-paradox/01-concepts.md
          - m04-friendship-paradox/02-coding.qmd
          - m04-friendship-paradox/03-exercises.md
      - section: "M05: Clustering"
        contents:
          - m05-clustering/00-preparation.md
          - m05-clustering/01-concepts.qmd
          - m05-clustering/02-coding.qmd
          - m05-clustering/03-exercises.qmd
      - section: "M06: Centrality"
        contents:
          - m06-centrality/00-preparation.md
          - m06-centrality/01-concepts.qmd
          - m06-centrality/02-coding.qmd
          - m06-centrality/03-exercises.md
      - section: "M07: Random Walks"
        contents:
          - m07-random-walks/00-preparation.md
          - m07-random-walks/01-concepts.qmd
          - m07-random-walks/02-coding.qmd
          - m07-random-walks/03-exercises.qmd
      - section: "M08: Embedding"
        contents:
          - m08-embedding/00-preparation.md
          - m08-embedding/01-concepts.md
          - m08-embedding/02-coding.qmd
          - m08-embedding/03-exercises.md
          - m08-embedding/04-appendix.md
      - section: "M09: Graph Neural Networks"
        contents:
          - m09-graph-neural-networks/00-preparation.md
          - m09-graph-neural-networks/01-concepts.md
          - m09-graph-neural-networks/02-coding.qmd
          - m09-graph-neural-networks/03-exercises.qmd
          - m09-graph-neural-networks/04-appendix.qmd

  navbar:
    logo: logo.jpg
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Intro"
        menu:
          - text: "Why Networks?"
            file: intro/why-networks.qmd
          - text: "Setup"
            file: intro/setup.qmd
          - text: "Quiz Dojo"
            file: dojo/quiz-dojo.qmd
      - text: "Foundations"
        menu:
          - text: "─── M01: Euler Tour ───"
          - text: "Preparation"
            file: m01-euler_tour/00-preparation.qmd
          - text: "Concepts"
            file: m01-euler_tour/01-concepts.qmd
          - text: "Coding"
            file: m01-euler_tour/02-coding.qmd
          - text: "Exercises"
            file: m01-euler_tour/03-exercises.qmd
          - text: "Advanced"
            file: m01-euler_tour/04-advanced.qmd
          - text: "─── M02: Small World ───"
          - text: "Preparation"
            file: m02-small-world/00-preparation.qmd
          - text: "Concepts"
            file: m02-small-world/01-concepts.qmd
          - text: "Coding"
            file: m02-small-world/02-coding.qmd
          - text: "Exercises"
            file: m02-small-world/03-exercises.md
          - text: "Appendix"
            file: m02-small-world/04-appendix.qmd
          - text: "─── M03: Robustness ───"
          - text: "Preparation"
            file: m03-robustness/00-preparation.md
          - text: "Concepts"
            file: m03-robustness/01-concepts.qmd
          - text: "Coding"
            file: m03-robustness/02-coding.qmd
          - text: "Exercises"
            file: m03-robustness/03-exercises.qmd
          - text: "Appendix"
            file: m03-robustness/04-appendix.md
      - text: "Core Topics"
        menu:
          - text: "─── M04: Friendship Paradox ───"
          - text: "Preparation"
            file: m04-friendship-paradox/00-preparation.md
          - text: "Concepts"
            file: m04-friendship-paradox/01-concepts.md
          - text: "Coding"
            file: m04-friendship-paradox/02-coding.qmd
          - text: "Exercises"
            file: m04-friendship-paradox/03-exercises.md
          - text: "─── M05: Clustering ───"
          - text: "Preparation"
            file: m05-clustering/00-preparation.md
          - text: "Concepts"
            file: m05-clustering/01-concepts.qmd
          - text: "Coding"
            file: m05-clustering/02-coding.qmd
          - text: "Exercises"
            file: m05-clustering/03-exercises.qmd
          - text: "─── M06: Centrality ───"
          - text: "Preparation"
            file: m06-centrality/00-preparation.md
          - text: "Concepts"
            file: m06-centrality/01-concepts.qmd
          - text: "Coding"
            file: m06-centrality/02-coding.qmd
          - text: "Exercises"
            file: m06-centrality/03-exercises.md
      - text: "Advanced Topics"
        menu:
          - text: "─── M07: Random Walks ───"
          - text: "Preparation"
            file: m07-random-walks/00-preparation.md
          - text: "Concepts"
            file: m07-random-walks/01-concepts.qmd
          - text: "Coding"
            file: m07-random-walks/02-coding.qmd
          - text: "Exercises"
            file: m07-random-walks/03-exercises.qmd
          - text: "─── M08: Embedding ───"
          - text: "Preparation"
            file: m08-embedding/00-preparation.md
          - text: "Concepts"
            file: m08-embedding/01-concepts.md
          - text: "Coding"
            file: m08-embedding/02-coding.qmd
          - text: "Exercises"
            file: m08-embedding/03-exercises.md
          - text: "Appendix"
            file: m08-embedding/04-appendix.md
          - text: "─── M09: Graph Neural Networks ───"
          - text: "Preparation"
            file: m09-graph-neural-networks/00-preparation.md
          - text: "Concepts"
            file: m09-graph-neural-networks/01-concepts.md
          - text: "Coding"
            file: m09-graph-neural-networks/02-coding.qmd
          - text: "Exercises"
            file: m09-graph-neural-networks/03-exercises.qmd
          - text: "Appendix"
            file: m09-graph-neural-networks/04-appendix.qmd

execute:
  enabled: false  # Disable execution for initial migration
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - scss/style.scss
    toc: false
    page-layout: full
    toc-depth: 2
    number-sections: true
    number-depth: 2
    html-math-method: katex
    code-fold: false
    code-copy: hover
    code-tools: true
    fontsize: 21px
    margin-left: 50px
    margin-right: 50px
    css:
      - assets/custom.css

# Add a bibtex file so that we can create citations
bibliography: references.bib

